openapi: 3.0.2
info:
  title: Reflectoring
  description: "Tutorials on Spring Boot and Java."
  termsOfService: http://swagger.io/terms/
  contact:
    email: petros.stergioulas94@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
externalDocs:
  description: Find out more about Reflectoring
  url: https://reflectoring.io/about/
servers:
  - url: https://reflectoring.swagger.io/v2
tags:
  - name: presupuesto
    description: operaciones para presupuesto
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
paths:
  /presupuesto/{id}:
    get:
      tags:
        - presupuesto
      summary: Obtener un presupuesto por su ID
      operationId: obtenerPresupuestoPorID
      parameters:
        - name: id
          in: path
          description: ID del presupuesto a obtener
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Presupuesto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Presupuesto'
        '404':
          description: Presupuesto no encontrado
        '500':
          description: Error del servidor
  /presupuesto:
    post:
      tags:
        - presupuesto
      summary: Crear un nuevo presupuesto
      operationId: crearPresupuesto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Presupuesto'
      responses:
        '201':
          description: Presupuesto creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Presupuesto'
        '400':
          description: Solicitud inválida
        '500':
          description: Error del servidor

components:
  schemas:
    Presupuesto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fecha:
          type: string
          format: date
          description: Fecha del presupuesto
        estado:
          type: string
          enum:
            - emitido
            - listado
          description: Estado del presupuesto
        cantidadEjemplares:
          type: integer
          description: Cantidad de ejemplares del presupuesto
          format: int64
        descripcion:
          type: string
          description: Descripción del trabajo
        idCliente:
          type: integer
          format: int64
          description: ID del Cliente
        formato:
          type: object
          properties:
            ancho:
              type: number
              description: Ancho en mm del formato.
            alto:
              type: number
              description: Alto en mm del formato.
          required:
            - ancho
            - alto
          description: Formato en mm final del trabajo.
        pliegoImpresion:
          type: object
          properties:
            ancho:
              type: number
              description: Ancho en mm del soporte de impresión.
            alto:
              type: number
              description: Alto en mm del soporte de impresión.
          required:
            - ancho
            - alto
          description: Formato en mm del soporte de impresión.
        maquina:
          type: array
          items:
            type: string
            enum:
              - Plotter de impresión
              - Plotter de corte
              - Laminadora
              - Manipulado
              # Agrega más máquinas según sea necesario
          uniqueItems: true
          description: Lista de máquinas seleccionadas.
        soporte:
          type: array
          items:
            type: string
            enum:
              - Vinilo monomérico de corte
              - Vinilo polimérico de corte
              - Vinilo monomérico de impresión
              - Vinilo polimérico de impresión
              - Vinilo textil de impresión
              - Laminado monomérico brillo
              - Laminado polimérico brillo
              - Laminado monomérico mate
              - Laminado polimérico mate
              - Laminado suelo
              - Imán
              - Mupi
              - Lienzo
              - Tela
              # Agrega más máquinas según sea necesario
          uniqueItems: true
          description: Lista de soportes seleccionados.
        costeTotal:
          type: number
          format: float
          description: Coste total del trabajo (sin margen de beneficios)
        margenBeneficio:
          type: integer
          format: int32
          description: Porcentaje de beneficio (0%-100%)
        beneficio:
          type: number
          format: float
          description: Margen de beneficio del trabajo
        precioUnitario:
          type: number
          format: float
          description: Precio por unidad de ejemplar
        importeTotal:
          type: number
          format: float
          description: Importe total a pagar por el cliente (coste del trabajo)
